AWS RDS Baseline
mitre/aws-rds-microsoft-sql-server-2017-cis-baseline pull request #1
Opened 2022-04-14 01:51 UTC by karikarshivani

All the profile errors have been addressed. Please let me know if I missed anything!

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

2022-04-14 01:52 UTC, karikarshivani commented on inspec.yml
> +  url: https://github.com/mitre/microsoft-sql-server-2017-cis-baseline/archive/v1.2.0.tar.gz
I'll update the branch name when the PR for the baseline has been approved and merged. Thanks!

2022-05-04 20:45 UTC, wdower approved these changes
LGTM, thanks!

2022-06-09 21:35 UTC, ejaronne requested changes
- update depends reference to main.tar.gz (not 1.2.0)
- update README exec instructions to use main.tar.gz (not master)
- update README "full heimdall server" url to point to heimdall2 repo not old heimdall

2022-06-10 02:22 UTC, ejaronne approved these changes

2022-06-10 12:40 UTC, karikarshivani commented on inspec.yml
> +  url: https://github.com/mitre/microsoft-sql-server-2017-cis-baseline/archive/v1.2.0.tar.gz
Updated the branch name

2022-06-10 12:42 UTC, karikarshivani commented
> * update depends reference to main.tar.gz (not 1.2.0)
> * update README exec instructions to use main.tar.gz (not master)
> * update README "full heimdall server" url to point to heimdall2 repo not old heimdall

Thanks for making these updates! I ran the profile - it's ready to be merged!

2022-06-10 17:08 UTC, merged